<?php

use Illuminate\Database\Seeder;

class KabupatenSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('wil_kabupaten')->insert(
            [
                [ 'kode_kabkot' => '101',  'provinsi_id' =>'11',  'nama_kabkot' => 'KABUPATEN SIMEULUE' ],
                [ 'kode_kabkot' => '102',  'provinsi_id' =>'11',  'nama_kabkot' => 'KABUPATEN ACEH SINGKIL' ],
                [ 'kode_kabkot' => '103',  'provinsi_id' =>'11',  'nama_kabkot' => 'KABUPATEN ACEH SELATAN' ],
                [ 'kode_kabkot' => '104',  'provinsi_id' =>'11',  'nama_kabkot' => 'KABUPATEN ACEH TENGGARA' ],
                [ 'kode_kabkot' => '105',  'provinsi_id' =>'11',  'nama_kabkot' => 'KABUPATEN ACEH TIMUR' ],
                [ 'kode_kabkot' => '106',  'provinsi_id' =>'11',  'nama_kabkot' => 'KABUPATEN ACEH TENGAH' ],
                [ 'kode_kabkot' => '107',  'provinsi_id' =>'11',  'nama_kabkot' => 'KABUPATEN ACEH BARAT' ],
                [ 'kode_kabkot' => '108',  'provinsi_id' =>'11',  'nama_kabkot' => 'KABUPATEN ACEH BESAR' ],
                [ 'kode_kabkot' => '109',  'provinsi_id' =>'11',  'nama_kabkot' => 'KABUPATEN PIDIE' ],
                [ 'kode_kabkot' => '1110', 'provinsi_id' => '11', 'nama_kabkot' =>  'KABUPATEN BIREUEN' ],
                [ 'kode_kabkot' => '1111', 'provinsi_id' => '11', 'nama_kabkot' =>  'KABUPATEN ACEH UTARA' ],
                [ 'kode_kabkot' => '1112', 'provinsi_id' => '11', 'nama_kabkot' =>  'KABUPATEN ACEH BARAT DAYA' ],
                [ 'kode_kabkot' => '1113', 'provinsi_id' => '11', 'nama_kabkot' =>  'KABUPATEN GAYO LUES' ],
                [ 'kode_kabkot' => '1114', 'provinsi_id' => '11', 'nama_kabkot' =>  'KABUPATEN ACEH TAMIANG' ],
                [ 'kode_kabkot' => '1115', 'provinsi_id' => '11', 'nama_kabkot' =>  'KABUPATEN NAGAN RAYA' ],
                [ 'kode_kabkot' => '1116', 'provinsi_id' => '11', 'nama_kabkot' =>  'KABUPATEN ACEH JAYA' ],
                [ 'kode_kabkot' => '1117', 'provinsi_id' => '11', 'nama_kabkot' =>  'KABUPATEN BENER MERIAH' ],
                [ 'kode_kabkot' => '1118', 'provinsi_id' => '11', 'nama_kabkot' =>  'KABUPATEN PIDIE JAYA' ],
                [ 'kode_kabkot' => '1171', 'provinsi_id' => '11', 'nama_kabkot' =>  'KOTA BANDA ACEH' ],
                [ 'kode_kabkot' => '1172', 'provinsi_id' => '11', 'nama_kabkot' =>  'KOTA SABANG' ],
                [ 'kode_kabkot' => '1173', 'provinsi_id' => '11', 'nama_kabkot' =>  'KOTA LANGSA' ],
                [ 'kode_kabkot' => '1174', 'provinsi_id' => '11', 'nama_kabkot' =>  'KOTA LHOKSEUMAWE' ],
                [ 'kode_kabkot' => '1175', 'provinsi_id' => '11', 'nama_kabkot' =>  'KOTA SUBULUSSALAM' ],
                [ 'kode_kabkot' => '1201', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN NIAS' ],
                [ 'kode_kabkot' => '1202', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN MANDAILING NATAL' ],
                [ 'kode_kabkot' => '1203', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN TAPANULI SELATAN' ],
                [ 'kode_kabkot' => '1204', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN TAPANULI TENGAH' ],
                [ 'kode_kabkot' => '1205', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN TAPANULI UTARA' ],
                [ 'kode_kabkot' => '1206', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN TOBA SAMOSIR' ],
                [ 'kode_kabkot' => '1207', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN LABUHAN BATU' ],
                [ 'kode_kabkot' => '1208', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN ASAHAN' ],
                [ 'kode_kabkot' => '1209', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN SIMALUNGUN' ],
                [ 'kode_kabkot' => '1210', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN DAIRI' ],
                [ 'kode_kabkot' => '1211', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN KARO' ],
                [ 'kode_kabkot' => '1212', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN DELI SERDANG' ],
                [ 'kode_kabkot' => '1213', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN LANGKAT' ],
                [ 'kode_kabkot' => '1214', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN NIAS SELATAN' ],
                [ 'kode_kabkot' => '1215', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN HUMBANG HASUNDUTAN' ],
                [ 'kode_kabkot' => '1216', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN PAKPAK BHARAT' ],
                [ 'kode_kabkot' => '1217', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN SAMOSIR' ],
                [ 'kode_kabkot' => '1218', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN SERDANG BEDAGAI' ],
                [ 'kode_kabkot' => '1219', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN BATU BARA' ],
                [ 'kode_kabkot' => '1220', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN PADANG LAWAS UTARA' ],
                [ 'kode_kabkot' => '1221', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN PADANG LAWAS' ],
                [ 'kode_kabkot' => '1222', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN LABUHAN BATU SELATAN' ],
                [ 'kode_kabkot' => '1223', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN LABUHAN BATU UTARA' ],
                [ 'kode_kabkot' => '1224', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN NIAS UTARA' ],
                [ 'kode_kabkot' => '1225', 'provinsi_id' => '12', 'nama_kabkot' =>  'KABUPATEN NIAS BARAT' ],
                [ 'kode_kabkot' => '1271', 'provinsi_id' => '12', 'nama_kabkot' =>  'KOTA SIBOLGA' ],
                [ 'kode_kabkot' => '1272', 'provinsi_id' => '12', 'nama_kabkot' =>  'KOTA TANJUNG BALAI' ],
                [ 'kode_kabkot' => '1273', 'provinsi_id' => '12', 'nama_kabkot' =>  'KOTA PEMATANG SIANTAR' ],
                [ 'kode_kabkot' => '1274', 'provinsi_id' => '12', 'nama_kabkot' =>  'KOTA TEBING TINGGI' ],
                [ 'kode_kabkot' => '1275', 'provinsi_id' => '12', 'nama_kabkot' =>  'KOTA MEDAN' ],
                [ 'kode_kabkot' => '1276', 'provinsi_id' => '12', 'nama_kabkot' =>  'KOTA BINJAI' ],
                [ 'kode_kabkot' => '1277', 'provinsi_id' => '12', 'nama_kabkot' =>  'KOTA PADANGSIDIMPUAN' ],
                [ 'kode_kabkot' => '1278', 'provinsi_id' => '12', 'nama_kabkot' =>  'KOTA GUNUNGSITOLI' ],
                [ 'kode_kabkot' => '1301', 'provinsi_id' => '13', 'nama_kabkot' =>  'KABUPATEN KEPULAUAN MENTAWAI' ],
                [ 'kode_kabkot' => '1302', 'provinsi_id' => '13', 'nama_kabkot' =>  'KABUPATEN PESISIR SELATAN' ],
                [ 'kode_kabkot' => '1303', 'provinsi_id' => '13', 'nama_kabkot' =>  'KABUPATEN SOLOK' ],
                [ 'kode_kabkot' => '1304', 'provinsi_id' => '13', 'nama_kabkot' =>  'KABUPATEN SIJUNJUNG' ],
                [ 'kode_kabkot' => '1305', 'provinsi_id' => '13', 'nama_kabkot' =>  'KABUPATEN TANAH DATAR' ],
                [ 'kode_kabkot' => '1306', 'provinsi_id' => '13', 'nama_kabkot' =>  'KABUPATEN PADANG PARIAMAN' ],
                [ 'kode_kabkot' => '1307', 'provinsi_id' => '13', 'nama_kabkot' =>  'KABUPATEN AGAM' ],
                [ 'kode_kabkot' => '1308', 'provinsi_id' => '13', 'nama_kabkot' =>  'KABUPATEN LIMA PULUH KOTA' ],
                [ 'kode_kabkot' => '1309', 'provinsi_id' => '13', 'nama_kabkot' =>  'KABUPATEN PASAMAN' ],
                [ 'kode_kabkot' => '1310', 'provinsi_id' => '13', 'nama_kabkot' =>  'KABUPATEN SOLOK SELATAN' ],
                [ 'kode_kabkot' => '1311', 'provinsi_id' => '13', 'nama_kabkot' =>  'KABUPATEN DHARMASRAYA' ],
                [ 'kode_kabkot' => '1312', 'provinsi_id' => '13', 'nama_kabkot' =>  'KABUPATEN PASAMAN BARAT' ],
                [ 'kode_kabkot' => '1371', 'provinsi_id' => '13', 'nama_kabkot' =>  'KOTA PADANG' ],
                [ 'kode_kabkot' => '1372', 'provinsi_id' => '13', 'nama_kabkot' =>  'KOTA SOLOK' ],
                [ 'kode_kabkot' => '1373', 'provinsi_id' => '13', 'nama_kabkot' =>  'KOTA SAWAH LUNTO' ],
                [ 'kode_kabkot' => '1374', 'provinsi_id' => '13', 'nama_kabkot' =>  'KOTA PADANG PANJANG' ],
                [ 'kode_kabkot' => '1375', 'provinsi_id' => '13', 'nama_kabkot' =>  'KOTA BUKITTINGGI' ],
                [ 'kode_kabkot' => '1376', 'provinsi_id' => '13', 'nama_kabkot' =>  'KOTA PAYAKUMBUH' ],
                [ 'kode_kabkot' => '1377', 'provinsi_id' => '13', 'nama_kabkot' =>  'KOTA PARIAMAN' ],
                [ 'kode_kabkot' => '1401', 'provinsi_id' => '14', 'nama_kabkot' =>  'KABUPATEN KUANTAN SINGINGI' ],
                [ 'kode_kabkot' => '1402', 'provinsi_id' => '14', 'nama_kabkot' =>  'KABUPATEN INDRAGIRI HULU' ],
                [ 'kode_kabkot' => '1403', 'provinsi_id' => '14', 'nama_kabkot' =>  'KABUPATEN INDRAGIRI HILIR' ],
                [ 'kode_kabkot' => '1404', 'provinsi_id' => '14', 'nama_kabkot' =>  'KABUPATEN PELALAWAN' ],
                [ 'kode_kabkot' => '1405', 'provinsi_id' => '14', 'nama_kabkot' =>  'KABUPATEN S I A K' ],
                [ 'kode_kabkot' => '1406', 'provinsi_id' => '14', 'nama_kabkot' =>  'KABUPATEN KAMPAR' ],
                [ 'kode_kabkot' => '1407', 'provinsi_id' => '14', 'nama_kabkot' =>  'KABUPATEN ROKAN HULU' ],
                [ 'kode_kabkot' => '1408', 'provinsi_id' => '14', 'nama_kabkot' =>  'KABUPATEN BENGKALIS' ],
                [ 'kode_kabkot' => '1409', 'provinsi_id' => '14', 'nama_kabkot' =>  'KABUPATEN ROKAN HILIR' ],
                [ 'kode_kabkot' => '1410', 'provinsi_id' => '14', 'nama_kabkot' =>  'KABUPATEN KEPULAUAN MERANTI' ],
                [ 'kode_kabkot' => '1471', 'provinsi_id' => '14', 'nama_kabkot' =>  'KOTA PEKANBARU' ],
                [ 'kode_kabkot' => '1473', 'provinsi_id' => '14', 'nama_kabkot' =>  'KOTA D U M A I' ],
                [ 'kode_kabkot' => '1501', 'provinsi_id' => '15', 'nama_kabkot' =>  'KABUPATEN KERINCI' ],
                [ 'kode_kabkot' => '1502', 'provinsi_id' => '15', 'nama_kabkot' =>  'KABUPATEN MERANGIN' ],
                [ 'kode_kabkot' => '1503', 'provinsi_id' => '15', 'nama_kabkot' =>  'KABUPATEN SAROLANGUN' ],
                [ 'kode_kabkot' => '1504', 'provinsi_id' => '15', 'nama_kabkot' =>  'KABUPATEN BATANG HARI' ],
                [ 'kode_kabkot' => '1505', 'provinsi_id' => '15', 'nama_kabkot' =>  'KABUPATEN MUARO JAMBI' ],
                [ 'kode_kabkot' => '1506', 'provinsi_id' => '15', 'nama_kabkot' =>  'KABUPATEN TANJUNG JABUNG TIMUR' ],
                [ 'kode_kabkot' => '1507', 'provinsi_id' => '15', 'nama_kabkot' =>  'KABUPATEN TANJUNG JABUNG BARAT' ],
                [ 'kode_kabkot' => '1508', 'provinsi_id' => '15', 'nama_kabkot' =>  'KABUPATEN TEBO' ],
                [ 'kode_kabkot' => '1509', 'provinsi_id' => '15', 'nama_kabkot' =>  'KABUPATEN BUNGO' ],
                [ 'kode_kabkot' => '1571', 'provinsi_id' => '15', 'nama_kabkot' =>  'KOTA JAMBI' ],
                [ 'kode_kabkot' => '1572', 'provinsi_id' => '15', 'nama_kabkot' =>  'KOTA SUNGAI PENUH' ],
                [ 'kode_kabkot' => '1601', 'provinsi_id' => '16', 'nama_kabkot' =>  'KABUPATEN OGAN KOMERING ULU' ],
                [ 'kode_kabkot' => '1602'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KABUPATEN OGAN KOMERING ILIR' ],
                [ 'kode_kabkot' => '1603'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KABUPATEN MUARA ENIM' ],
                [ 'kode_kabkot' => '1604'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KABUPATEN LAHAT' ],
                [ 'kode_kabkot' => '1605'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KABUPATEN MUSI RAWAS' ],
                [ 'kode_kabkot' => '1606'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KABUPATEN MUSI BANYUASIN' ],
                [ 'kode_kabkot' => '1607'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KABUPATEN BANYU ASIN' ],
                [ 'kode_kabkot' => '1608'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KABUPATEN OGAN KOMERING ULU SELATAN' ],
                [ 'kode_kabkot' => '1609'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KABUPATEN OGAN KOMERING ULU TIMUR' ],
                [ 'kode_kabkot' => '1610'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KABUPATEN OGAN ILIR' ],
                [ 'kode_kabkot' => '1611'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KABUPATEN EMPAT LAWANG' ],
                [ 'kode_kabkot' => '1612'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR' ],
                [ 'kode_kabkot' => '1613'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KABUPATEN MUSI RAWAS UTARA' ],
                [ 'kode_kabkot' => '1671'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KOTA PALEMBANG' ],
                [ 'kode_kabkot' => '1672'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KOTA PRABUMULIH' ],
                [ 'kode_kabkot' => '1673'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KOTA PAGAR ALAM' ],
                [ 'kode_kabkot' => '1674'  , 'provinsi_id' => '16'  , 'nama_kabkot' => 'KOTA LUBUKLINGGAU' ],
                [ 'kode_kabkot' => '1701'  , 'provinsi_id' => '17'  , 'nama_kabkot' => 'KABUPATEN BENGKULU SELATAN' ],
                [ 'kode_kabkot' => '1702'  , 'provinsi_id' => '17'  , 'nama_kabkot' => 'KABUPATEN REJANG LEBONG' ],
                [ 'kode_kabkot' => '1703'  , 'provinsi_id' => '17'  , 'nama_kabkot' => 'KABUPATEN BENGKULU UTARA' ],
                [ 'kode_kabkot' => '1704'  , 'provinsi_id' => '17'  , 'nama_kabkot' => 'KABUPATEN KAUR' ],
                [ 'kode_kabkot' => '1705'  , 'provinsi_id' => '17'  , 'nama_kabkot' => 'KABUPATEN SELUMA' ],
                [ 'kode_kabkot' => '1706'  , 'provinsi_id' => '17'  , 'nama_kabkot' => 'KABUPATEN MUKOMUKO' ],
                [ 'kode_kabkot' => '1707'  , 'provinsi_id' => '17'  , 'nama_kabkot' => 'KABUPATEN LEBONG' ],
                [ 'kode_kabkot' => '1708'  , 'provinsi_id' => '17'  , 'nama_kabkot' => 'KABUPATEN KEPAHIANG' ],
                [ 'kode_kabkot' => '1709'  , 'provinsi_id' => '17'  , 'nama_kabkot' => 'KABUPATEN BENGKULU TENGAH' ],
                [ 'kode_kabkot' => '1771'  , 'provinsi_id' => '17'  , 'nama_kabkot' => 'KOTA BENGKULU' ],
                [ 'kode_kabkot' => '1801'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KABUPATEN LAMPUNG BARAT' ],
                [ 'kode_kabkot' => '1802'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KABUPATEN TANGGAMUS' ],
                [ 'kode_kabkot' => '1803'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KABUPATEN LAMPUNG SELATAN' ],
                [ 'kode_kabkot' => '1804'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KABUPATEN LAMPUNG TIMUR' ],
                [ 'kode_kabkot' => '1805'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KABUPATEN LAMPUNG TENGAH' ],
                [ 'kode_kabkot' => '1806'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KABUPATEN LAMPUNG UTARA' ],
                [ 'kode_kabkot' => '1807'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KABUPATEN WAY KANAN' ],
                [ 'kode_kabkot' => '1808'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KABUPATEN TULANGBAWANG' ],
                [ 'kode_kabkot' => '1809'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KABUPATEN PESAWARAN' ],
                [ 'kode_kabkot' => '1810'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KABUPATEN PRINGSEWU' ],
                [ 'kode_kabkot' => '1811'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KABUPATEN MESUJI' ],
                [ 'kode_kabkot' => '1812'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KABUPATEN TULANG BAWANG BARAT' ],
                [ 'kode_kabkot' => '1813'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KABUPATEN PESISIR BARAT' ],
                [ 'kode_kabkot' => '1871'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KOTA BANDAR LAMPUNG' ],
                [ 'kode_kabkot' => '1872'  , 'provinsi_id' => '18'  , 'nama_kabkot' => 'KOTA METRO' ],
                [ 'kode_kabkot' => '1901'  , 'provinsi_id' => '19'  , 'nama_kabkot' => 'KABUPATEN BANGKA' ],
                [ 'kode_kabkot' => '1902'  , 'provinsi_id' => '19'  , 'nama_kabkot' => 'KABUPATEN BELITUNG' ],
                [ 'kode_kabkot' => '1903'  , 'provinsi_id' => '19'  , 'nama_kabkot' => 'KABUPATEN BANGKA BARAT' ],
                [ 'kode_kabkot' => '1904'  , 'provinsi_id' => '19'  , 'nama_kabkot' => 'KABUPATEN BANGKA TENGAH' ],
                [ 'kode_kabkot' => '1905'  , 'provinsi_id' => '19'  , 'nama_kabkot' => 'KABUPATEN BANGKA SELATAN' ],
                [ 'kode_kabkot' => '1906'  , 'provinsi_id' => '19'  , 'nama_kabkot' => 'KABUPATEN BELITUNG TIMUR' ],
                [ 'kode_kabkot' => '1971'  , 'provinsi_id' => '19'  , 'nama_kabkot' => 'KOTA PANGKAL PINANG' ],
                [ 'kode_kabkot' => '2101'  , 'provinsi_id' => '21'  , 'nama_kabkot' => 'KABUPATEN KARIMUN' ],
                [ 'kode_kabkot' => '2102'  , 'provinsi_id' => '21'  , 'nama_kabkot' => 'KABUPATEN BINTAN' ],
                [ 'kode_kabkot' => '2103'  , 'provinsi_id' => '21'  , 'nama_kabkot' => 'KABUPATEN NATUNA' ],
                [ 'kode_kabkot' => '2104'  , 'provinsi_id' => '21'  , 'nama_kabkot' => 'KABUPATEN LINGGA' ],
                [ 'kode_kabkot' => '2105'  , 'provinsi_id' => '21'  , 'nama_kabkot' => 'KABUPATEN KEPULAUAN ANAMBAS' ],
                [ 'kode_kabkot' => '2171'  , 'provinsi_id' => '21'  , 'nama_kabkot' => 'KOTA B A T A M' ],
                [ 'kode_kabkot' => '2172'  , 'provinsi_id' => '21'  , 'nama_kabkot' => 'KOTA TANJUNG PINANG' ],
                [ 'kode_kabkot' => '3101'  , 'provinsi_id' => '31'  , 'nama_kabkot' => 'KABUPATEN KEPULAUAN SERIBU' ],
                [ 'kode_kabkot' => '3171'  , 'provinsi_id' => '31'  , 'nama_kabkot' => 'KOTA JAKARTA SELATAN' ],
                [ 'kode_kabkot' => '3172'  , 'provinsi_id' => '31'  , 'nama_kabkot' => 'KOTA JAKARTA TIMUR' ],
                [ 'kode_kabkot' => '3173'  , 'provinsi_id' => '31'  , 'nama_kabkot' => 'KOTA JAKARTA PUSAT' ],
                [ 'kode_kabkot' => '3174'  , 'provinsi_id' => '31'  , 'nama_kabkot' => 'KOTA JAKARTA BARAT' ],
                [ 'kode_kabkot' => '3175'  , 'provinsi_id' => '31'  , 'nama_kabkot' => 'KOTA JAKARTA UTARA' ],
                [ 'kode_kabkot' => '3201'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN BOGOR' ],
                [ 'kode_kabkot' => '3202'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN SUKABUMI' ],
                [ 'kode_kabkot' => '3203'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN CIANJUR' ],
                [ 'kode_kabkot' => '3204'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN BANDUNG' ],
                [ 'kode_kabkot' => '3205'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN GARUT' ],
                [ 'kode_kabkot' => '3206'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN TASIKMALAYA' ],
                [ 'kode_kabkot' => '3207'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN CIAMIS' ],
                [ 'kode_kabkot' => '3208'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN KUNINGAN' ],
                [ 'kode_kabkot' => '3209'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN CIREBON' ],
                [ 'kode_kabkot' => '3210'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN MAJALENGKA' ],
                [ 'kode_kabkot' => '3211'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN SUMEDANG' ],
                [ 'kode_kabkot' => '3212'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN INDRAMAYU' ],
                [ 'kode_kabkot' => '3213'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN SUBANG' ],
                [ 'kode_kabkot' => '3214'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN PURWAKARTA' ],
                [ 'kode_kabkot' => '3215'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN KARAWANG' ],
                [ 'kode_kabkot' => '3216'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN BEKASI' ],
                [ 'kode_kabkot' => '3217'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN BANDUNG BARAT' ],
                [ 'kode_kabkot' => '3218'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KABUPATEN PANGANDARAN' ],
                [ 'kode_kabkot' => '3271'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KOTA BOGOR' ],
                [ 'kode_kabkot' => '3272'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KOTA SUKABUMI' ],
                [ 'kode_kabkot' => '3273'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KOTA BANDUNG' ],
                [ 'kode_kabkot' => '3274'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KOTA CIREBON' ],
                [ 'kode_kabkot' => '3275'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KOTA BEKASI' ],
                [ 'kode_kabkot' => '3276'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KOTA DEPOK' ],
                [ 'kode_kabkot' => '3277'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KOTA CIMAHI' ],
                [ 'kode_kabkot' => '3278'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KOTA TASIKMALAYA' ],
                [ 'kode_kabkot' => '3279'  , 'provinsi_id' => '32'  , 'nama_kabkot' => 'KOTA BANJAR' ],
                [ 'kode_kabkot' => '3301'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN CILACAP' ],
                [ 'kode_kabkot' => '3302'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN BANYUMAS' ],
                [ 'kode_kabkot' => '3303'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN PURBALINGGA' ],
                [ 'kode_kabkot' => '3304'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN BANJARNEGARA' ],
                [ 'kode_kabkot' => '3305'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN KEBUMEN' ],
                [ 'kode_kabkot' => '3306'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN PURWOREJO' ],
                [ 'kode_kabkot' => '3307'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN WONOSOBO' ],
                [ 'kode_kabkot' => '3308'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN MAGELANG' ],
                [ 'kode_kabkot' => '3309'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN BOYOLALI' ],
                [ 'kode_kabkot' => '3310'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN KLATEN' ],
                [ 'kode_kabkot' => '3311'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN SUKOHARJO' ],
                [ 'kode_kabkot' => '3312'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN WONOGIRI' ],
                [ 'kode_kabkot' => '3313'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN KARANGANYAR' ],
                [ 'kode_kabkot' => '3314'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN SRAGEN' ],
                [ 'kode_kabkot' => '3315'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN GROBOGAN' ],
                [ 'kode_kabkot' => '3316'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN BLORA' ],
                [ 'kode_kabkot' => '3317'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN REMBANG' ],
                [ 'kode_kabkot' => '3318'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN PATI' ],
                [ 'kode_kabkot' => '3319'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN KUDUS' ],
                [ 'kode_kabkot' => '3320'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN JEPARA' ],
                [ 'kode_kabkot' => '3321'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN DEMAK' ],
                [ 'kode_kabkot' => '3322'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN SEMARANG' ],
                [ 'kode_kabkot' => '3323'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN TEMANGGUNG' ],
                [ 'kode_kabkot' => '3324'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN KENDAL' ],
                [ 'kode_kabkot' => '3325'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN BATANG' ],
                [ 'kode_kabkot' => '3326'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN PEKALONGAN' ],
                [ 'kode_kabkot' => '3327'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN PEMALANG' ],
                [ 'kode_kabkot' => '3328'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN TEGAL' ],
                [ 'kode_kabkot' => '3329'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KABUPATEN BREBES' ],
                [ 'kode_kabkot' => '3371'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KOTA MAGELANG' ],
                [ 'kode_kabkot' => '3372'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KOTA SURAKARTA' ],
                [ 'kode_kabkot' => '3373'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KOTA SALATIGA' ],
                [ 'kode_kabkot' => '3374'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KOTA SEMARANG' ],
                [ 'kode_kabkot' => '3375'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KOTA PEKALONGAN' ],
                [ 'kode_kabkot' => '3376'  , 'provinsi_id' => '33'  , 'nama_kabkot' => 'KOTA TEGAL' ],
                [ 'kode_kabkot' => '3401'  , 'provinsi_id' => '34'  , 'nama_kabkot' => 'KABUPATEN KULON PROGO' ],
                [ 'kode_kabkot' => '3402'  , 'provinsi_id' => '34'  , 'nama_kabkot' => 'KABUPATEN BANTUL' ],
                [ 'kode_kabkot' => '3403'  , 'provinsi_id' => '34'  , 'nama_kabkot' => 'KABUPATEN GUNUNG KIDUL' ],
                [ 'kode_kabkot' => '3404'  , 'provinsi_id' => '34'  , 'nama_kabkot' => 'KABUPATEN SLEMAN' ],
                [ 'kode_kabkot' => '3471'  , 'provinsi_id' => '34'  , 'nama_kabkot' => 'KOTA YOGYAKARTA' ],
                [ 'kode_kabkot' => '3501'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN PACITAN' ],
                [ 'kode_kabkot' => '3502'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN PONOROGO' ],
                [ 'kode_kabkot' => '3503'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN TRENGGALEK' ],
                [ 'kode_kabkot' => '3504'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN TULUNGAGUNG' ],
                [ 'kode_kabkot' => '3505'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN BLITAR' ],
                [ 'kode_kabkot' => '3506'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN KEDIRI' ],
                [ 'kode_kabkot' => '3507'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN MALANG' ],
                [ 'kode_kabkot' => '3508'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN LUMAJANG' ],
                [ 'kode_kabkot' => '3509'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN JEMBER' ],
                [ 'kode_kabkot' => '3510'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN BANYUWANGI' ],
                [ 'kode_kabkot' => '3511'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN BONDOWOSO' ],
                [ 'kode_kabkot' => '3512'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN SITUBONDO' ],
                [ 'kode_kabkot' => '3513'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN PROBOLINGGO' ],
                [ 'kode_kabkot' => '3514'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN PASURUAN' ],
                [ 'kode_kabkot' => '3515'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN SIDOARJO' ],
                [ 'kode_kabkot' => '3516'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN MOJOKERTO' ],
                [ 'kode_kabkot' => '3517'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN JOMBANG' ],
                [ 'kode_kabkot' => '3518'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN NGANJUK' ],
                [ 'kode_kabkot' => '3519'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN MADIUN' ],
                [ 'kode_kabkot' => '3520'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN MAGETAN' ],
                [ 'kode_kabkot' => '3521'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN NGAWI' ],
                [ 'kode_kabkot' => '3522'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN BOJONEGORO' ],
                [ 'kode_kabkot' => '3523'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN TUBAN' ],
                [ 'kode_kabkot' => '3524'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN LAMONGAN' ],
                [ 'kode_kabkot' => '3525'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN GRESIK' ],
                [ 'kode_kabkot' => '3526'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN BANGKALAN' ],
                [ 'kode_kabkot' => '3527'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN SAMPANG' ],
                [ 'kode_kabkot' => '3528'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN PAMEKASAN' ],
                [ 'kode_kabkot' => '3529'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KABUPATEN SUMENEP' ],
                [ 'kode_kabkot' => '3571'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KOTA KEDIRI' ],
                [ 'kode_kabkot' => '3572'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KOTA BLITAR' ],
                [ 'kode_kabkot' => '3573'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KOTA MALANG' ],
                [ 'kode_kabkot' => '3574'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KOTA PROBOLINGGO' ],
                [ 'kode_kabkot' => '3575'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KOTA PASURUAN' ],
                [ 'kode_kabkot' => '3576'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KOTA MOJOKERTO' ],
                [ 'kode_kabkot' => '3577'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KOTA MADIUN' ],
                [ 'kode_kabkot' => '3578'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KOTA SURABAYA' ],
                [ 'kode_kabkot' => '3579'  , 'provinsi_id' => '35'  , 'nama_kabkot' => 'KOTA BATU' ],
                [ 'kode_kabkot' => '3601'  , 'provinsi_id' => '36'  , 'nama_kabkot' => 'KABUPATEN PANDEGLANG' ],
                [ 'kode_kabkot' => '3602'  , 'provinsi_id' => '36'  , 'nama_kabkot' => 'KABUPATEN LEBAK' ],
                [ 'kode_kabkot' => '3603'  , 'provinsi_id' => '36'  , 'nama_kabkot' => 'KABUPATEN TANGERANG' ],
                [ 'kode_kabkot' => '3604'  , 'provinsi_id' => '36'  , 'nama_kabkot' => 'KABUPATEN SERANG' ],
                [ 'kode_kabkot' => '3671'  , 'provinsi_id' => '36'  , 'nama_kabkot' => 'KOTA TANGERANG' ],
                [ 'kode_kabkot' => '3672'  , 'provinsi_id' => '36'  , 'nama_kabkot' => 'KOTA CILEGON' ],
                [ 'kode_kabkot' => '3673'  , 'provinsi_id' => '36'  , 'nama_kabkot' => 'KOTA SERANG' ],
                [ 'kode_kabkot' => '3674'  , 'provinsi_id' => '36'  , 'nama_kabkot' => 'KOTA TANGERANG SELATAN' ],
                [ 'kode_kabkot' => '5101'  , 'provinsi_id' => '51'  , 'nama_kabkot' => 'KABUPATEN JEMBRANA' ],
                [ 'kode_kabkot' => '5102'  , 'provinsi_id' => '51'  , 'nama_kabkot' => 'KABUPATEN TABANAN' ],
                [ 'kode_kabkot' => '5103'  , 'provinsi_id' => '51'  , 'nama_kabkot' => 'KABUPATEN BADUNG' ],
                [ 'kode_kabkot' => '5104'  , 'provinsi_id' => '51'  , 'nama_kabkot' => 'KABUPATEN GIANYAR' ],
                [ 'kode_kabkot' => '5105'  , 'provinsi_id' => '51'  , 'nama_kabkot' => 'KABUPATEN KLUNGKUNG' ],
                [ 'kode_kabkot' => '5106'  , 'provinsi_id' => '51'  , 'nama_kabkot' => 'KABUPATEN BANGLI' ],
                [ 'kode_kabkot' => '5107'  , 'provinsi_id' => '51'  , 'nama_kabkot' => 'KABUPATEN KARANG ASEM' ],
                [ 'kode_kabkot' => '5108'  , 'provinsi_id' => '51'  , 'nama_kabkot' => 'KABUPATEN BULELENG' ],
                [ 'kode_kabkot' => '5171'  , 'provinsi_id' => '51'  , 'nama_kabkot' => 'KOTA DENPASAR' ],
                [ 'kode_kabkot' => '5201'  , 'provinsi_id' => '52'  , 'nama_kabkot' => 'KABUPATEN LOMBOK BARAT' ],
                [ 'kode_kabkot' => '5202'  , 'provinsi_id' => '52'  , 'nama_kabkot' => 'KABUPATEN LOMBOK TENGAH' ],
                [ 'kode_kabkot' => '5203'  , 'provinsi_id' => '52'  , 'nama_kabkot' => 'KABUPATEN LOMBOK TIMUR' ],
                [ 'kode_kabkot' => '5204'  , 'provinsi_id' => '52'  , 'nama_kabkot' => 'KABUPATEN SUMBAWA' ],
                [ 'kode_kabkot' => '5205'  , 'provinsi_id' => '52'  , 'nama_kabkot' => 'KABUPATEN DOMPU' ],
                [ 'kode_kabkot' => '5206'  , 'provinsi_id' => '52'  , 'nama_kabkot' => 'KABUPATEN BIMA' ],
                [ 'kode_kabkot' => '5207'  , 'provinsi_id' => '52'  , 'nama_kabkot' => 'KABUPATEN SUMBAWA BARAT' ],
                [ 'kode_kabkot' => '5208'  , 'provinsi_id' => '52'  , 'nama_kabkot' => 'KABUPATEN LOMBOK UTARA' ],
                [ 'kode_kabkot' => '5271'  , 'provinsi_id' => '52'  , 'nama_kabkot' => 'KOTA MATARAM' ],
                [ 'kode_kabkot' => '5272'  , 'provinsi_id' => '52'  , 'nama_kabkot' => 'KOTA BIMA' ],
                [ 'kode_kabkot' => '5301'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN SUMBA BARAT' ],
                [ 'kode_kabkot' => '5302'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN SUMBA TIMUR' ],
                [ 'kode_kabkot' => '5303'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN KUPANG' ],
                [ 'kode_kabkot' => '5304'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN TIMOR TENGAH SELATAN' ],
                [ 'kode_kabkot' => '5305'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN TIMOR TENGAH UTARA' ],
                [ 'kode_kabkot' => '5306'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN BELU' ],
                [ 'kode_kabkot' => '5307'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN ALOR' ],
                [ 'kode_kabkot' => '5308'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN LEMBATA' ],
                [ 'kode_kabkot' => '5309'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN FLORES TIMUR' ],
                [ 'kode_kabkot' => '5310'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN SIKKA' ],
                [ 'kode_kabkot' => '5311'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN ENDE' ],
                [ 'kode_kabkot' => '5312'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN NGADA' ],
                [ 'kode_kabkot' => '5313'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN MANGGARAI' ],
                [ 'kode_kabkot' => '5314'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN ROTE NDAO' ],
                [ 'kode_kabkot' => '5315'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN MANGGARAI BARAT' ],
                [ 'kode_kabkot' => '5316'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN SUMBA TENGAH' ],
                [ 'kode_kabkot' => '5317'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN SUMBA BARAT DAYA' ],
                [ 'kode_kabkot' => '5318'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN NAGEKEO' ],
                [ 'kode_kabkot' => '5319'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN MANGGARAI TIMUR' ],
                [ 'kode_kabkot' => '5320'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN SABU RAIJUA' ],
                [ 'kode_kabkot' => '5321'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KABUPATEN MALAKA' ],
                [ 'kode_kabkot' => '5371'  , 'provinsi_id' => '53'  , 'nama_kabkot' => 'KOTA KUPANG' ],
                [ 'kode_kabkot' => '6101'  , 'provinsi_id' => '61'  , 'nama_kabkot' => 'KABUPATEN SAMBAS' ],
                [ 'kode_kabkot' => '6102'  , 'provinsi_id' => '61'  , 'nama_kabkot' => 'KABUPATEN BENGKAYANG' ],
                [ 'kode_kabkot' => '6103'  , 'provinsi_id' => '61'  , 'nama_kabkot' => 'KABUPATEN LANDAK' ],
                [ 'kode_kabkot' => '6104'  , 'provinsi_id' => '61'  , 'nama_kabkot' => 'KABUPATEN MEMPAWAH' ],
                [ 'kode_kabkot' => '6105'  , 'provinsi_id' => '61'  , 'nama_kabkot' => 'KABUPATEN SANGGAU' ],
                [ 'kode_kabkot' => '6106'  , 'provinsi_id' => '61'  , 'nama_kabkot' => 'KABUPATEN KETAPANG' ],
                [ 'kode_kabkot' => '6107'  , 'provinsi_id' => '61'  , 'nama_kabkot' => 'KABUPATEN SINTANG' ],
                [ 'kode_kabkot' => '6108'  , 'provinsi_id' => '61'  , 'nama_kabkot' => 'KABUPATEN KAPUAS HULU' ],
                [ 'kode_kabkot' => '6109'  , 'provinsi_id' => '61'  , 'nama_kabkot' => 'KABUPATEN SEKADAU' ],
                [ 'kode_kabkot' => '6110'  , 'provinsi_id' => '61'  , 'nama_kabkot' => 'KABUPATEN MELAWI' ],
                [ 'kode_kabkot' => '6111'  , 'provinsi_id' => '61'  , 'nama_kabkot' => 'KABUPATEN KAYONG UTARA' ],
                [ 'kode_kabkot' => '6112'  , 'provinsi_id' => '61'  , 'nama_kabkot' => 'KABUPATEN KUBU RAYA' ],
                [ 'kode_kabkot' => '6171'  , 'provinsi_id' => '61'  , 'nama_kabkot' => 'KOTA PONTIANAK' ],
                [ 'kode_kabkot' => '6172'  , 'provinsi_id' => '61'  , 'nama_kabkot' => 'KOTA SINGKAWANG' ],
                [ 'kode_kabkot' => '6201'  , 'provinsi_id' => '62'  , 'nama_kabkot' => 'KABUPATEN KOTAWARINGIN BARAT' ],
                [ 'kode_kabkot' => '6202'  , 'provinsi_id' => '62'  , 'nama_kabkot' => 'KABUPATEN KOTAWARINGIN TIMUR' ],
                [ 'kode_kabkot' => '6203'  , 'provinsi_id' => '62'  , 'nama_kabkot' => 'KABUPATEN KAPUAS' ],
                [ 'kode_kabkot' => '6204'  , 'provinsi_id' => '62'  , 'nama_kabkot' => 'KABUPATEN BARITO SELATAN' ],
                [ 'kode_kabkot' => '6205'  , 'provinsi_id' => '62'  , 'nama_kabkot' => 'KABUPATEN BARITO UTARA' ],
                [ 'kode_kabkot' => '6206'  , 'provinsi_id' => '62'  , 'nama_kabkot' => 'KABUPATEN SUKAMARA' ],
                [ 'kode_kabkot' => '6207'  , 'provinsi_id' => '62'  , 'nama_kabkot' => 'KABUPATEN LAMANDAU' ],
                [ 'kode_kabkot' => '6208'  , 'provinsi_id' => '62'  , 'nama_kabkot' => 'KABUPATEN SERUYAN' ],
                [ 'kode_kabkot' => '6209'  , 'provinsi_id' => '62'  , 'nama_kabkot' => 'KABUPATEN KATINGAN' ],
                [ 'kode_kabkot' => '6210'  , 'provinsi_id' => '62'  , 'nama_kabkot' => 'KABUPATEN PULANG PISAU' ],
                [ 'kode_kabkot' => '6211'  , 'provinsi_id' => '62'  , 'nama_kabkot' => 'KABUPATEN GUNUNG MAS' ],
                [ 'kode_kabkot' => '6212'  , 'provinsi_id' => '62'  , 'nama_kabkot' => 'KABUPATEN BARITO TIMUR' ],
                [ 'kode_kabkot' => '6213'  , 'provinsi_id' => '62'  , 'nama_kabkot' => 'KABUPATEN MURUNG RAYA' ],
                [ 'kode_kabkot' => '6271'  , 'provinsi_id' => '62'  , 'nama_kabkot' => 'KOTA PALANGKA RAYA' ],
                [ 'kode_kabkot' => '6301'  , 'provinsi_id' => '63'  , 'nama_kabkot' => 'KABUPATEN TANAH LAUT' ],
                [ 'kode_kabkot' => '6302'  , 'provinsi_id' => '63'  , 'nama_kabkot' => 'KABUPATEN KOTA BARU' ],
                [ 'kode_kabkot' => '6303'  , 'provinsi_id' => '63'  , 'nama_kabkot' => 'KABUPATEN BANJAR' ],
                [ 'kode_kabkot' => '6304'  , 'provinsi_id' => '63'  , 'nama_kabkot' => 'KABUPATEN BARITO KUALA' ],
                [ 'kode_kabkot' => '6305'  , 'provinsi_id' => '63'  , 'nama_kabkot' => 'KABUPATEN TAPIN' ],
                [ 'kode_kabkot' => '6306'  , 'provinsi_id' => '63'  , 'nama_kabkot' => 'KABUPATEN HULU SUNGAI SELATAN' ],
                [ 'kode_kabkot' => '6307'  , 'provinsi_id' => '63'  , 'nama_kabkot' => 'KABUPATEN HULU SUNGAI TENGAH' ],
                [ 'kode_kabkot' => '6308'  , 'provinsi_id' => '63'  , 'nama_kabkot' => 'KABUPATEN HULU SUNGAI UTARA' ],
                [ 'kode_kabkot' => '6309'  , 'provinsi_id' => '63'  , 'nama_kabkot' => 'KABUPATEN TABALONG' ],
                [ 'kode_kabkot' => '6310'  , 'provinsi_id' => '63'  , 'nama_kabkot' => 'KABUPATEN TANAH BUMBU' ],
                [ 'kode_kabkot' => '6311'  , 'provinsi_id' => '63'  , 'nama_kabkot' => 'KABUPATEN BALANGAN' ],
                [ 'kode_kabkot' => '6371'  , 'provinsi_id' => '63'  , 'nama_kabkot' => 'KOTA BANJARMASIN' ],
                [ 'kode_kabkot' => '6372'  , 'provinsi_id' => '63'  , 'nama_kabkot' => 'KOTA BANJAR BARU' ],
                [ 'kode_kabkot' => '6401'  , 'provinsi_id' => '64'  , 'nama_kabkot' => 'KABUPATEN PASER' ],
                [ 'kode_kabkot' => '6402'  , 'provinsi_id' => '64'  , 'nama_kabkot' => 'KABUPATEN KUTAI BARAT' ],
                [ 'kode_kabkot' => '6403'  , 'provinsi_id' => '64'  , 'nama_kabkot' => 'KABUPATEN KUTAI KARTANEGARA' ],
                [ 'kode_kabkot' => '6404'  , 'provinsi_id' => '64'  , 'nama_kabkot' => 'KABUPATEN KUTAI TIMUR' ],
                [ 'kode_kabkot' => '6405'  , 'provinsi_id' => '64'  , 'nama_kabkot' => 'KABUPATEN BERAU' ],
                [ 'kode_kabkot' => '6409'  , 'provinsi_id' => '64'  , 'nama_kabkot' => 'KABUPATEN PENAJAM PASER UTARA' ],
                [ 'kode_kabkot' => '6411'  , 'provinsi_id' => '64'  , 'nama_kabkot' => 'KABUPATEN MAHAKAM HULU' ],
                [ 'kode_kabkot' => '6471'  , 'provinsi_id' => '64'  , 'nama_kabkot' => 'KOTA BALIKPAPAN' ],
                [ 'kode_kabkot' => '6472'  , 'provinsi_id' => '64'  , 'nama_kabkot' => 'KOTA SAMARINDA' ],
                [ 'kode_kabkot' => '6474'  , 'provinsi_id' => '64'  , 'nama_kabkot' => 'KOTA BONTANG' ],
                [ 'kode_kabkot' => '6501'  , 'provinsi_id' => '65'  , 'nama_kabkot' => 'KABUPATEN MALINAU' ],
                [ 'kode_kabkot' => '6502'  , 'provinsi_id' => '65'  , 'nama_kabkot' => 'KABUPATEN BULUNGAN' ],
                [ 'kode_kabkot' => '6503'  , 'provinsi_id' => '65'  , 'nama_kabkot' => 'KABUPATEN TANA TIDUNG' ],
                [ 'kode_kabkot' => '6504'  , 'provinsi_id' => '65'  , 'nama_kabkot' => 'KABUPATEN NUNUKAN' ],
                [ 'kode_kabkot' => '6571'  , 'provinsi_id' => '65'  , 'nama_kabkot' => 'KOTA TARAKAN' ],
                [ 'kode_kabkot' => '7101'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KABUPATEN BOLAANG MONGONDOW' ],
                [ 'kode_kabkot' => '7102'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KABUPATEN MINAHASA' ],
                [ 'kode_kabkot' => '7103'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KABUPATEN KEPULAUAN SANGIHE' ],
                [ 'kode_kabkot' => '7104'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KABUPATEN KEPULAUAN TALAUD' ],
                [ 'kode_kabkot' => '7105'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KABUPATEN MINAHASA SELATAN' ],
                [ 'kode_kabkot' => '7106'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KABUPATEN MINAHASA UTARA' ],
                [ 'kode_kabkot' => '7107'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KABUPATEN BOLAANG MONGONDOW UTARA' ],
                [ 'kode_kabkot' => '7108'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KABUPATEN SIAU TAGULANDANG BIARO' ],
                [ 'kode_kabkot' => '7109'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KABUPATEN MINAHASA TENGGARA' ],
                [ 'kode_kabkot' => '7110'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KABUPATEN BOLAANG MONGONDOW SELATAN' ],
                [ 'kode_kabkot' => '7111'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KABUPATEN BOLAANG MONGONDOW TIMUR' ],
                [ 'kode_kabkot' => '7171'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KOTA MANADO' ],
                [ 'kode_kabkot' => '7172'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KOTA BITUNG' ],
                [ 'kode_kabkot' => '7173'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KOTA TOMOHON' ],
                [ 'kode_kabkot' => '7174'  , 'provinsi_id' => '71'  , 'nama_kabkot' => 'KOTA KOTAMOBAGU' ],
                [ 'kode_kabkot' => '7201'  , 'provinsi_id' => '72'  , 'nama_kabkot' => 'KABUPATEN BANGGAI KEPULAUAN' ],
                [ 'kode_kabkot' => '7202'  , 'provinsi_id' => '72'  , 'nama_kabkot' => 'KABUPATEN BANGGAI' ],
                [ 'kode_kabkot' => '7203'  , 'provinsi_id' => '72'  , 'nama_kabkot' => 'KABUPATEN MOROWALI' ],
                [ 'kode_kabkot' => '7204'  , 'provinsi_id' => '72'  , 'nama_kabkot' => 'KABUPATEN POSO' ],
                [ 'kode_kabkot' => '7205'  , 'provinsi_id' => '72'  , 'nama_kabkot' => 'KABUPATEN DONGGALA' ],
                [ 'kode_kabkot' => '7206'  , 'provinsi_id' => '72'  , 'nama_kabkot' => 'KABUPATEN TOLI-TOLI' ],
                [ 'kode_kabkot' => '7207'  , 'provinsi_id' => '72'  , 'nama_kabkot' => 'KABUPATEN BUOL' ],
                [ 'kode_kabkot' => '7208'  , 'provinsi_id' => '72'  , 'nama_kabkot' => 'KABUPATEN PARIGI MOUTONG' ],
                [ 'kode_kabkot' => '7209'  , 'provinsi_id' => '72'  , 'nama_kabkot' => 'KABUPATEN TOJO UNA-UNA' ],
                [ 'kode_kabkot' => '7210'  , 'provinsi_id' => '72'  , 'nama_kabkot' => 'KABUPATEN SIGI' ],
                [ 'kode_kabkot' => '7211'  , 'provinsi_id' => '72'  , 'nama_kabkot' => 'KABUPATEN BANGGAI LAUT' ],
                [ 'kode_kabkot' => '7212'  , 'provinsi_id' => '72'  , 'nama_kabkot' => 'KABUPATEN MOROWALI UTARA' ],
                [ 'kode_kabkot' => '7271'  , 'provinsi_id' => '72'  , 'nama_kabkot' => 'KOTA PALU' ],
                [ 'kode_kabkot' => '7301'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN KEPULAUAN SELAYAR' ],
                [ 'kode_kabkot' => '7302'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN BULUKUMBA' ],
                [ 'kode_kabkot' => '7303'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN BANTAENG' ],
                [ 'kode_kabkot' => '7304'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN JENEPONTO' ],
                [ 'kode_kabkot' => '7305'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN TAKALAR' ],
                [ 'kode_kabkot' => '7306'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN GOWA' ],
                [ 'kode_kabkot' => '7307'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN SINJAI' ],
                [ 'kode_kabkot' => '7308'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN MAROS' ],
                [ 'kode_kabkot' => '7309'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN' ],
                [ 'kode_kabkot' => '7310'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN BARRU' ],
                [ 'kode_kabkot' => '7311'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN BONE' ],
                [ 'kode_kabkot' => '7312'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN SOPPENG' ],
                [ 'kode_kabkot' => '7313'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN WAJO' ],
                [ 'kode_kabkot' => '7314'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN SIDENRENG RAPPANG' ],
                [ 'kode_kabkot' => '7315'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN PINRANG' ],
                [ 'kode_kabkot' => '7316'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN ENREKANG' ],
                [ 'kode_kabkot' => '7317'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN LUWU' ],
                [ 'kode_kabkot' => '7318'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN TANA TORAJA' ],
                [ 'kode_kabkot' => '7322'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN LUWU UTARA' ],
                [ 'kode_kabkot' => '7325'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN LUWU TIMUR' ],
                [ 'kode_kabkot' => '7326'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KABUPATEN TORAJA UTARA' ],
                [ 'kode_kabkot' => '7371'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KOTA MAKASSAR' ],
                [ 'kode_kabkot' => '7372'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KOTA PAREPARE' ],
                [ 'kode_kabkot' => '7373'  , 'provinsi_id' => '73'  , 'nama_kabkot' => 'KOTA PALOPO' ],
                [ 'kode_kabkot' => '7401'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN BUTON' ],
                [ 'kode_kabkot' => '7402'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN MUNA' ],
                [ 'kode_kabkot' => '7403'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN KONAWE' ],
                [ 'kode_kabkot' => '7404'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN KOLAKA' ],
                [ 'kode_kabkot' => '7405'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN KONAWE SELATAN' ],
                [ 'kode_kabkot' => '7406'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN BOMBANA' ],
                [ 'kode_kabkot' => '7407'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN WAKATOBI' ],
                [ 'kode_kabkot' => '7408'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN KOLAKA UTARA' ],
                [ 'kode_kabkot' => '7409'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN BUTON UTARA' ],
                [ 'kode_kabkot' => '7410'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN KONAWE UTARA' ],
                [ 'kode_kabkot' => '7411'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN KOLAKA TIMUR' ],
                [ 'kode_kabkot' => '7412'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN KONAWE KEPULAUAN' ],
                [ 'kode_kabkot' => '7413'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN MUNA BARAT' ],
                [ 'kode_kabkot' => '7414'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN BUTON TENGAH' ],
                [ 'kode_kabkot' => '7415'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KABUPATEN BUTON SELATAN' ],
                [ 'kode_kabkot' => '7471'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KOTA KENDARI' ],
                [ 'kode_kabkot' => '7472'  , 'provinsi_id' => '74'  , 'nama_kabkot' => 'KOTA BAUBAU' ],
                [ 'kode_kabkot' => '7501'  , 'provinsi_id' => '75'  , 'nama_kabkot' => 'KABUPATEN BOALEMO' ],
                [ 'kode_kabkot' => '7502'  , 'provinsi_id' => '75'  , 'nama_kabkot' => 'KABUPATEN GORONTALO' ],
                [ 'kode_kabkot' => '7503'  , 'provinsi_id' => '75'  , 'nama_kabkot' => 'KABUPATEN POHUWATO' ],
                [ 'kode_kabkot' => '7504'  , 'provinsi_id' => '75'  , 'nama_kabkot' => 'KABUPATEN BONE BOLANGO' ],
                [ 'kode_kabkot' => '7505'  , 'provinsi_id' => '75'  , 'nama_kabkot' => 'KABUPATEN GORONTALO UTARA' ],
                [ 'kode_kabkot' => '7571'  , 'provinsi_id' => '75'  , 'nama_kabkot' => 'KOTA GORONTALO' ],
                [ 'kode_kabkot' => '7601'  , 'provinsi_id' => '76'  , 'nama_kabkot' => 'KABUPATEN MAJENE' ],
                [ 'kode_kabkot' => '7602'  , 'provinsi_id' => '76'  , 'nama_kabkot' => 'KABUPATEN POLEWALI MANDAR' ],
                [ 'kode_kabkot' => '7603'  , 'provinsi_id' => '76'  , 'nama_kabkot' => 'KABUPATEN MAMASA' ],
                [ 'kode_kabkot' => '7604'  , 'provinsi_id' => '76'  , 'nama_kabkot' => 'KABUPATEN MAMUJU' ],
                [ 'kode_kabkot' => '7605'  , 'provinsi_id' => '76'  , 'nama_kabkot' => 'KABUPATEN MAMUJU UTARA' ],
                [ 'kode_kabkot' => '7606'  , 'provinsi_id' => '76'  , 'nama_kabkot' => 'KABUPATEN MAMUJU TENGAH' ],
                [ 'kode_kabkot' => '8101'  , 'provinsi_id' => '81'  , 'nama_kabkot' => 'KABUPATEN MALUKU TENGGARA BARAT' ],
                [ 'kode_kabkot' => '8102'  , 'provinsi_id' => '81'  , 'nama_kabkot' => 'KABUPATEN MALUKU TENGGARA' ],
                [ 'kode_kabkot' => '8103'  , 'provinsi_id' => '81'  , 'nama_kabkot' => 'KABUPATEN MALUKU TENGAH' ],
                [ 'kode_kabkot' => '8104'  , 'provinsi_id' => '81'  , 'nama_kabkot' => 'KABUPATEN BURU' ],
                [ 'kode_kabkot' => '8105'  , 'provinsi_id' => '81'  , 'nama_kabkot' => 'KABUPATEN KEPULAUAN ARU' ],
                [ 'kode_kabkot' => '8106'  , 'provinsi_id' => '81'  , 'nama_kabkot' => 'KABUPATEN SERAM BAGIAN BARAT' ],
                [ 'kode_kabkot' => '8107'  , 'provinsi_id' => '81'  , 'nama_kabkot' => 'KABUPATEN SERAM BAGIAN TIMUR' ],
                [ 'kode_kabkot' => '8108'  , 'provinsi_id' => '81'  , 'nama_kabkot' => 'KABUPATEN MALUKU BARAT DAYA' ],
                [ 'kode_kabkot' => '8109'  , 'provinsi_id' => '81'  , 'nama_kabkot' => 'KABUPATEN BURU SELATAN' ],
                [ 'kode_kabkot' => '8171'  , 'provinsi_id' => '81'  , 'nama_kabkot' => 'KOTA AMBON' ],
                [ 'kode_kabkot' => '8172'  , 'provinsi_id' => '81'  , 'nama_kabkot' => 'KOTA TUAL' ],
                [ 'kode_kabkot' => '8201'  , 'provinsi_id' => '82'  , 'nama_kabkot' => 'KABUPATEN HALMAHERA BARAT' ],
                [ 'kode_kabkot' => '8202'  , 'provinsi_id' => '82'  , 'nama_kabkot' => 'KABUPATEN HALMAHERA TENGAH' ],
                [ 'kode_kabkot' => '8203'  , 'provinsi_id' => '82'  , 'nama_kabkot' => 'KABUPATEN KEPULAUAN SULA' ],
                [ 'kode_kabkot' => '8204'  , 'provinsi_id' => '82'  , 'nama_kabkot' => 'KABUPATEN HALMAHERA SELATAN' ],
                [ 'kode_kabkot' => '8205'  , 'provinsi_id' => '82'  , 'nama_kabkot' => 'KABUPATEN HALMAHERA UTARA' ],
                [ 'kode_kabkot' => '8206'  , 'provinsi_id' => '82'  , 'nama_kabkot' => 'KABUPATEN HALMAHERA TIMUR' ],
                [ 'kode_kabkot' => '8207'  , 'provinsi_id' => '82'  , 'nama_kabkot' => 'KABUPATEN PULAU MOROTAI' ],
                [ 'kode_kabkot' => '8208'  , 'provinsi_id' => '82'  , 'nama_kabkot' => 'KABUPATEN PULAU TALIABU' ],
                [ 'kode_kabkot' => '8271'  , 'provinsi_id' => '82'  , 'nama_kabkot' => 'KOTA TERNATE' ],
                [ 'kode_kabkot' => '8272'  , 'provinsi_id' => '82'  , 'nama_kabkot' => 'KOTA TIDORE KEPULAUAN' ],
                [ 'kode_kabkot' => '9101'  , 'provinsi_id' => '91'  , 'nama_kabkot' => 'KABUPATEN FAKFAK' ],
                [ 'kode_kabkot' => '9102'  , 'provinsi_id' => '91'  , 'nama_kabkot' => 'KABUPATEN KAIMANA' ],
                [ 'kode_kabkot' => '9103'  , 'provinsi_id' => '91'  , 'nama_kabkot' => 'KABUPATEN TELUK WONDAMA' ],
                [ 'kode_kabkot' => '9104'  , 'provinsi_id' => '91'  , 'nama_kabkot' => 'KABUPATEN TELUK BINTUNI' ],
                [ 'kode_kabkot' => '9105'  , 'provinsi_id' => '91'  , 'nama_kabkot' => 'KABUPATEN MANOKWARI' ],
                [ 'kode_kabkot' => '9106'  , 'provinsi_id' => '91'  , 'nama_kabkot' => 'KABUPATEN SORONG SELATAN' ],
                [ 'kode_kabkot' => '9107'  , 'provinsi_id' => '91'  , 'nama_kabkot' => 'KABUPATEN SORONG' ],
                [ 'kode_kabkot' => '9108'  , 'provinsi_id' => '91'  , 'nama_kabkot' => 'KABUPATEN RAJA AMPAT' ],
                [ 'kode_kabkot' => '9109'  , 'provinsi_id' => '91'  , 'nama_kabkot' => 'KABUPATEN TAMBRAUW' ],
                [ 'kode_kabkot' => '9110'  , 'provinsi_id' => '91'  , 'nama_kabkot' => 'KABUPATEN MAYBRAT' ],
                [ 'kode_kabkot' => '9111'  , 'provinsi_id' => '91'  , 'nama_kabkot' => 'KABUPATEN MANOKWARI SELATAN' ],
                [ 'kode_kabkot' => '9112'  , 'provinsi_id' => '91'  , 'nama_kabkot' => 'KABUPATEN PEGUNUNGAN ARFAK' ],
                [ 'kode_kabkot' => '9171'  , 'provinsi_id' => '91'  , 'nama_kabkot' => 'KOTA SORONG' ],
                [ 'kode_kabkot' => '9401'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN MERAUKE' ],
                [ 'kode_kabkot' => '9402'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN JAYAWIJAYA' ],
                [ 'kode_kabkot' => '9403'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN JAYAPURA' ],
                [ 'kode_kabkot' => '9404'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN NABIRE' ],
                [ 'kode_kabkot' => '9408'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN KEPULAUAN YAPEN' ],
                [ 'kode_kabkot' => '9409'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN BIAK NUMFOR' ],
                [ 'kode_kabkot' => '9410'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN PANIAI' ],
                [ 'kode_kabkot' => '9411'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN PUNCAK JAYA' ],
                [ 'kode_kabkot' => '9412'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN MIMIKA' ],
                [ 'kode_kabkot' => '9413'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN BOVEN DIGOEL' ],
                [ 'kode_kabkot' => '9414'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN MAPPI' ],
                [ 'kode_kabkot' => '9415'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN ASMAT' ],
                [ 'kode_kabkot' => '9416'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN YAHUKIMO' ],
                [ 'kode_kabkot' => '9417'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN PEGUNUNGAN BINTANG' ],
                [ 'kode_kabkot' => '9418'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN TOLIKARA' ],
                [ 'kode_kabkot' => '9419'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN SARMI' ],
                [ 'kode_kabkot' => '9420'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN KEEROM' ],
                [ 'kode_kabkot' => '9426'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN WAROPEN' ],
                [ 'kode_kabkot' => '9427'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN SUPIORI' ],
                [ 'kode_kabkot' => '9428'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN MAMBERAMO RAYA' ],
                [ 'kode_kabkot' => '9429'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN NDUGA' ],
                [ 'kode_kabkot' => '9430'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN LANNY JAYA' ],
                [ 'kode_kabkot' => '9431'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN MAMBERAMO TENGAH' ],
                [ 'kode_kabkot' => '9432'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN YALIMO' ],
                [ 'kode_kabkot' => '9433'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN PUNCAK' ],
                [ 'kode_kabkot' => '9434'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN DOGIYAI' ],
                [ 'kode_kabkot' => '9435'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN INTAN JAYA' ],
                [ 'kode_kabkot' => '9436'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KABUPATEN DEIYAI' ],
                [ 'kode_kabkot' => '9471'  , 'provinsi_id' => '94'  , 'nama_kabkot' => 'KOTA JAYAPURA']
            ]
            
        );
    }
}


